### ISSUE TITLE
db-hint

### ISSUE THREAD

**Issue by vitaly-t** [fooey/edulisting2-api-server#1]
instead of doing double-conversion like this (first, `ARRAY`, then `::text[]`):
```sql
ANY(${stateSlug}::text[])
```
```js
 return query(res, next, QUERY_GEO_STATE, { stateSlug: stateSlug.split(',') });
```
you can format it directly: 

```sql
ANY(${stateSlug:csv})
```
```js
 return query(res, next, QUERY_GEO_STATE, { stateSlug: stateSlug.split(',') });
```

**Comment by fooey** [comment]
Thanks! That does make things a bit cleaner.

And thanks for the library, I've been really happy with pg-promise so far.
